### ISSUE TITLE
There's an existing library called algo4j

### ISSUE THREAD

**Issue by ice1000** [HuajiStudio/graph4j#1]
It's an algorithm library using JNI (in order to be faster), which contains some graph theory algorithms' implementation.
See https:/github.com/ice1000/algo4j
How about merging these two projects together or making one the subproject of the other?

**Comment by EntropyIncreaser** [comment]
Actually this repo is for printing graph structures, so there are big differences.

**Comment by ice1000** [comment]
That sounds cool. So you're going to build a GUI application?

**Comment by LasmGratel** [comment]
BTW JNA is much more better than JNI

**Comment by ice1000** [comment]
I use JNI for performance, so abstraction is not that significant. For abstraction you can focus on Kotlin Native, which is supposed to be the best JNI solution -- one language, two targets.
